version: '3'

services:
  app:
    container_name: app-php
    build:
      context: ./.setup/build
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-php

  mysql:
    image: mysql:8.0.11
    container_name: app-php-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      TZ: "America/Sao_Paulo"
    volumes:
      - .docker-volumes/mysql:/var/lib/mysql
      - .setup/build/dev/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-php

  nginx:
    container_name: app-php-nginx
    image: nginx:latest
    ports:
      - "88:80"
    volumes:
      - ./:/var/www
      - ./.setup/build/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge